### ISSUE TITLE
Switch over to ephem for sunrise/sunset times

### ISSUE THREAD

**Issue by therivenman** [therivenman/domus#1]
We should switch over to using `ephem` instead of `astral`, because of the more accurate times afforded by using lat/long for location.

We should also use the google maps API, so that the user can just input their home address in the settings file and it will calculate the lat and long automatically.

Also, we could think about caching this information so it doesn't have to be done each time the program starts up.

**Comment by Materdaddy** [comment]
ephem switched, lat/long retrieved from google's geocode API, cached using pickle.
